- name: remove apache and data directory from client machine
  hosts: webserver
  tasks:
     - name: remove directory
       file:
         path: /data
         state: absent

     - name: remove apache
       yum:
         name:
          - httpd
          - httpd-tools
         state: absent
      
     - name: remove index.html file
       file:
         path: /var/www/html/index.html
         state: absent

